//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoreGraphicAttachments.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MoreGraphicAttachments.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Select the clothing initialization color mode 的本地化字符串。
        /// </summary>
        internal static string Config_ClothesColorChanceMode {
            get {
                return ResourceManager.GetString("Config_ClothesColorChanceMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Does the offspring inherit the clothes color 的本地化字符串。
        /// </summary>
        internal static string Config_ClothesColorInherit {
            get {
                return ResourceManager.GetString("Config_ClothesColorInherit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Custom chance of colored clothing appearing 的本地化字符串。
        /// </summary>
        internal static string Config_CustomClothesColorChance {
            get {
                return ResourceManager.GetString("Config_CustomClothesColorChance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Always Colored 的本地化字符串。
        /// </summary>
        internal static string Label_AlwaysColored {
            get {
                return ResourceManager.GetString("Label_AlwaysColored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unified Custom 的本地化字符串。
        /// </summary>
        internal static string Label_Custom {
            get {
                return ResourceManager.GetString("Label_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 From Config 的本地化字符串。
        /// </summary>
        internal static string Label_Default {
            get {
                return ResourceManager.GetString("Label_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clothes Color 的本地化字符串。
        /// </summary>
        internal static string Slot_ClothesColor {
            get {
                return ResourceManager.GetString("Slot_ClothesColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clothes Type 的本地化字符串。
        /// </summary>
        internal static string Slot_ClothesType {
            get {
                return ResourceManager.GetString("Slot_ClothesType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hair Bundle Type 的本地化字符串。
        /// </summary>
        internal static string Slot_HairBundleType {
            get {
                return ResourceManager.GetString("Slot_HairBundleType", resourceCulture);
            }
        }
    }
}
